install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - scoop install rust
build: off
test_script:
  - rustc did_.rs
  - rustc do_.rs
  - rustc todo_.rs
  - set TODO_PRINT_PATH=1
  - todo_
  - do_ Write tests
  - do_ Setup CI
  - todo_
  - did_ Write tests
  - did_ Setup CI
  - todo_
