.PHONY: all clean

src := $(wildcard *.rs)
bin := $(patsubst %.rs,%.exe,$(src))

all: .todo_list

.todo_list: $(bin)
	set TODO_LIST=.todo_list
	set PATH=$(shell echo %cd%)
	@echo.> todo_
	@todo_
	@echo.> do_ Write tests
	@do_ Write tests
	@echo.> do_ Setup CI
	@do_ Setup CI
	@echo.> todo_
	@todo_
	@echo.> did_ Write tests
	@did_ Write tests
	@echo.> did_ Setup CI
	@did_ Setup CI
	@echo> todo_
	@todo_

%.exe: %.rs
	rustc $^
	-del /q /f .todo_list

clean:
	-del /q /f $(bin) .todo_list
